name: food_delivery_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  firebase_storage: ^12.2.0
  delightful_toast: ^1.1.0
  dash_chat_2: ^0.0.21
  image_picker: ^1.1.2
  path: ^1.9.0
  curved_navigation_bar: ^1.0.6
  flutter_stripe: ^11.0.0
  http: ^1.2.2
  random_string: ^2.3.1
  cached_network_image: ^3.3.1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    # Uncomment and add your image assets here.
    - assets/images/burger.png
    - assets/images/ice-cream.png
    - assets/images/pizza.png
    - assets/images/salad.png
    - assets/images/Salad.jpg
    - assets/images/Delivery1.jpg
    - assets/images/Delivery2.jpg
    - assets/images/Delivery3.jpg
    - assets/images/Wallet.png


  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-SemiBold.ttf

